### PR TITLE
Factor out CDDL

### LINKED ISSUE #80: Align draft text and CDDL
We should have one only source of truth to avoid future out-of-sync between prose and CDDL as much as possible.

This is quite hefty because it needs some mods in the upstream CDDL repo too.

### PR DESCRIPTION
**Pull request by thomas-fossati**
Fix #80

### CODE REVIEW

**Comment by nedmsmith** [comment]
I'm not sure what to review. There is lots of green and circle cl is failing.

**Comment by thomas-fossati** [comment]
> I'm not sure what to review. There is lots of green and circle cl is failing.

circle is failing because it's not configured.  I think the only one with enough permissions to fix it is @henkbirkholz.  Regarding the green stuff, it's the code that's been transplanted from the draft.

**Review by henkbirkholz — APPROVED** [review]
complies locally for me, will merge

**Comment by nedmsmith** [comment]
Merge OK since local compiles work even though circleci fails.

**Pull request merged**
